# -*- coding: utf-8 -*-
"""BERT_Embeddings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FXGWgWuqa4l3Dx7WM5wXPmZmShD2ffl
"""

!pip install transformers

import torch
import pandas as pd
import numpy as np

df = pd.read_csv("caption_id.csv")
sentences = df.Caption.values

a=np.empty(((int)(sentences.shape[0]/2),768))
from transformers import BertModel
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

model.eval()
for i in range(sen.shape[0]):
    input_sentence = torch.tensor(tokenizer.encode(sen[i])).unsqueeze(0)
    out = model(input_sentence)
    embeddings_of_last_layer = out[0]
    cls_embeddings = embeddings_of_last_layer[0].clone().detach().requires_grad_(False)

    a[i]=np.mean(np.array(cls_embeddings),axis=0)
    model.zero_grad()

bc=pd.DataFrame(a)
bc.to_csv('embbedings1.csv')